name: Build and Release

on:
  push:
    branches: [ main ]
    tags: ["v*"]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 16 2019" ..
          msbuild MyProgram.sln /p:Configuration=Release

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          name: MyProgram.exe
          path: build/Release/MyProgram.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
