name: Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [win-64, macos-11.0]
    steps:
      - name: Set up Python ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [[ "${{ matrix.os }}" == "win-64" ]]; then
            pip install github-release-cli
          else
            /bin/zsh -c "$(curl -fsSL https://gitee.com/cunkai/HomebrewCN/raw/master/Homebrew.sh)
            y
            brew install github/gh/gh
          fi
      - name: Build and Package
        run: |
          pyinstaller --onefile --clean --name=mathquiz mathquiz.py
          mv dist ../dist/${{ matrix.os }}/ && rm -rf build __pycache__
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OS: ${{ matrix.os }}
        run: |
          gh auth login --with-token <<< "${GITHUB_TOKEN}"
          gh release create -t v1.0.0 -n "Math Quiz App ($OS)" ../dist/$OS/mathquiz
