# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Test Build Python Exe

on:
  push:
    branches:
    - main
    # - release/*

permissions:
  actions: write

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test Build Python Exe
      uses: james-bond-007/pyinstaller-build@master
      with:
        main: ./main
        artifact: Program
        icon: /src/main
        python_version: 3.x
        pyinstaller_version: 5.10.0
        use-dependencies: true
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: python_linux
        path: ${{ github.workspace }}/dist
        
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: build exe with pyinstaller
        shell: bash
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
          pip install pyinstaller==5.10.0
          pyinstaller -w -p pyside6 -p ./src --add-data ./src/*:./src --icon ./src/main.ico --onefile main.py
          # chown -R $(stat -c '%u:%g' .) ./dist
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: python_exe
          path: dist
  build_macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: build exe with pyinstaller
        shell: bash
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
          pip install pyinstaller==5.10.0
          pyinstaller -w -p pyside6 -p ./src --add-data './src/*':./src --icon ./src/main.icns --onefile main.py
          # chown -R $(stat -c '%u:%g' .) ./dist
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: python_mac
          path: dist