name: Publish

on:
  push:
    branches:
    - main
    # - release/*

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: mything
            asset_name: mything-linux-amd64
          - os: windows-latest
            artifact_name: mything.exe
            asset_name: mything-windows-amd64
          - os: macos-latest
            artifact_name: mything.dmg
            asset_name: mything-macos-amd64
    

    steps:
    - uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x
    - name: build exe with pyinstaller
      shell: bash
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt
        pip install pyinstaller==5.10.0
        pyinstaller --clean -y --dist ./dist --name main --onefile ./src/main.py
        # chown -R $(stat -c '%u:%g' .) ./dist
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ github.workspace }}/dist

        