name: Publish

on:
  push:
    branches:
    - main
    # - release/*

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: mything
            asset_name: mything-linux-amd64
          - os: windows-latest
            artifact_name: mything.exe
            asset_name: mything-windows-amd64
          - os: macos-latest
            artifact_name: mything
            asset_name: mything-macos-amd64
    

    steps:
    - uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x
    - name: build exe with pyinstaller
      shell: bash
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt
        pip install pyinstaller==5.10.0
        pyinstaller --clean -y --dist ./dist --name main --onefile ./src/main.py
        chown -R --reference=../dist
        
    - name: Test Build Python Exe
      uses: eric2788/pyinstaller-build@master
      with:
        main: ./src/main
        python_version: 3.x
        pyinstaller_version: 5.10.0
        use-dependencies: true
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: dist/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}

        