name: Release

on:
  workflow_run:
    workflows: ["Test Build Python Exe"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: Math_Quiz_*
        path: dist

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        title: Release ${{ github.event.workflow_run.conclusion }}
        body: |
          Changes in this release:
          - Add feature X
          - Fix bug Y
        token: ${{ secrets.GITHUB_TOKEN }}
