name: Release Build Artifacts

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: Math_Quiz  # 这里使用你之前上传的 artifact 的名称
          path: dist

      - name: Extract Artifacts
        run: |
          unzip dist/Math_Quiz_linux.zip -d dist/Math_Quiz_linux
          unzip dist/Math_Quiz_exe.zip -d dist/Math_Quiz_exe
          unzip dist/Math_Quiz_mac.zip -d dist/Math_Quiz_mac

      # 这里添加任何你需要的发布步骤，例如将文件打包成 zip，创建安装包等。

      - name: Upload Artifacts to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/Math_Quiz_linux
          asset_name: Math_Quiz_linux.zip
          asset_content_type: application/zip

      - name: Upload Artifacts to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/Math_Quiz_exe
          asset_name: Math_Quiz_exe.zip
          asset_content_type: application/zip

      - name: Upload Artifacts to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/Math_Quiz_mac
          asset_name: Math_Quiz_mac.zip
          asset_content_type: application/zip
