name: Release

on:
  workflow_run:
    workflows: ["Test Build Python Exe"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bumpversion

      - name: Bump Version
        run: |
          bumpversion --config-file setup.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        run: |
          tag=$(git describe --tags --abbrev=0)
          echo "Creating release $tag"
          curl -sSL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -X POST -d '{"tag_name": "'"$tag"'", "name": "'"$tag"'", "draft": false, "prerelease": false}' \
            "https://api.github.com/repos/${{ github.repository }}/releases"
          echo "::set-output name=tag::$tag"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifacts to Release
        run: |
          curl -sSL -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/zip" \
            --data-binary "@dist/Math_Quiz.zip" \
            "https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.create_release.outputs.tag }}/assets?name=Math_Quiz.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
